### ISSUE TITLE
Take screenshot from console

### ISSUE THREAD

**Issue by pankajparashar** [codepo8/dearconsole#6]
Firefox & Safari have helper functions to take a screenshot from console, as indicated here,

https://canidev.tools/capture-screenshot-console/firefox
https://canidev.tools/capture-screenshot-console/safari

Would this be a good fit for the Dear Console series, as it will not work across all browsers?
If yes, then browser support is also something we should consider adding to the project, although it does take away the simplicity of the project.

**Comment by codepo8** [comment]
I did not know this. You might be right, I should add a browser field.
